//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:2.0.50727.5466
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.borger.dk/2009/WSArticleExport/v1/types", ClrNamespace="www.borger.dk._2009.WSArticleExport.v1.types")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.borger.dk/2009/WSArticleExport/v2/types", ClrNamespace="www.borger.dk._2009.WSArticleExport.v2.types")]

namespace www.borger.dk._2009.WSArticleExport.v1.types
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleDescription", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class ArticleDescription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        private string ArticleUrlField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] FormServiceAreasField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] FormTaskAreasField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] FormTasksField;
        
        private System.DateTime LastUpdatedField;
        
        private System.DateTime PublishingDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleUrl
        {
            get
            {
                return this.ArticleUrlField;
            }
            set
            {
                this.ArticleUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] FormServiceAreas
        {
            get
            {
                return this.FormServiceAreasField;
            }
            set
            {
                this.FormServiceAreasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] FormTaskAreas
        {
            get
            {
                return this.FormTaskAreasField;
            }
            set
            {
                this.FormTaskAreasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] FormTasks
        {
            get
            {
                return this.FormTasksField;
            }
            set
            {
                this.FormTasksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishingDate
        {
            get
            {
                return this.PublishingDateField;
            }
            set
            {
                this.PublishingDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormServiceArea", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormServiceArea : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormServiceAreaNameField;
        
        private string FormServiceAreaNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormServiceAreaName
        {
            get
            {
                return this.FormServiceAreaNameField;
            }
            set
            {
                this.FormServiceAreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormServiceAreaNumber
        {
            get
            {
                return this.FormServiceAreaNumberField;
            }
            set
            {
                this.FormServiceAreaNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTaskArea", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormTaskArea : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormTaskAreaNameField;
        
        private string FormTaskAreaNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormTaskAreaName
        {
            get
            {
                return this.FormTaskAreaNameField;
            }
            set
            {
                this.FormTaskAreaNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormTaskAreaNumber
        {
            get
            {
                return this.FormTaskAreaNumberField;
            }
            set
            {
                this.FormTaskAreaNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormTask", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormTask : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormTaskNameField;
        
        private string FormTaskNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormTaskName
        {
            get
            {
                return this.FormTaskNameField;
            }
            set
            {
                this.FormTaskNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormTaskNumber
        {
            get
            {
                return this.FormTaskNumberField;
            }
            set
            {
                this.FormTaskNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArticleHeaderField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        private string ArticleUrlField;
        
        private string ContentField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] FormServiceAreasField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] FormTaskAreasField;
        
        private www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] FormTasksField;
        
        private System.DateTime LastUpdatedField;
        
        private System.DateTime PublishingDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleHeader
        {
            get
            {
                return this.ArticleHeaderField;
            }
            set
            {
                this.ArticleHeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleUrl
        {
            get
            {
                return this.ArticleUrlField;
            }
            set
            {
                this.ArticleUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] FormServiceAreas
        {
            get
            {
                return this.FormServiceAreasField;
            }
            set
            {
                this.FormServiceAreasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] FormTaskAreas
        {
            get
            {
                return this.FormTaskAreasField;
            }
            set
            {
                this.FormTaskAreasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] FormTasks
        {
            get
            {
                return this.FormTasksField;
            }
            set
            {
                this.FormTasksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishingDate
        {
            get
            {
                return this.PublishingDateField;
            }
            set
            {
                this.PublishingDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleShortDescription", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class ArticleShortDescription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Municipality", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class Municipality : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MunicipalityCodeField;
        
        private string MunicipalityNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MunicipalityCode
        {
            get
            {
                return this.MunicipalityCodeField;
            }
            set
            {
                this.MunicipalityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MunicipalityName
        {
            get
            {
                return this.MunicipalityNameField;
            }
            set
            {
                this.MunicipalityNameField = value;
            }
        }
    }
}
namespace www.borger.dk._2009.WSArticleExport.v2.types
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://www.borger.dk/2009/WSArticleExport/v2/types")]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ParentIDField;
        
        private int SiteIDField;
        
        private string SiteNameField;
        
        private string SiteTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID
        {
            get
            {
                return this.ParentIDField;
            }
            set
            {
                this.ParentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID
        {
            get
            {
                return this.SiteIDField;
            }
            set
            {
                this.SiteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName
        {
            get
            {
                return this.SiteNameField;
            }
            set
            {
                this.SiteNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteTitle
        {
            get
            {
                return this.SiteTitleField;
            }
            set
            {
                this.SiteTitleField = value;
            }
        }
    }
}
namespace ITST.Borgerdk.Export.Common.WcfContracts
{
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ArticleExportException : System.ServiceModel.FaultExceptionOfArticleFaulttsA8QZpB
    {
        
        public ArticleExportException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
}
namespace System.ServiceModel
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException))]
    public partial class FaultExceptionOfArticleFaulttsA8QZpB : System.ServiceModel.FaultException
    {
        
        public FaultExceptionOfArticleFaulttsA8QZpB(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.borger.dk/2009/WSArticleExport/v1", ConfigurationName="IArticleExport")]
public interface IArticleExport
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllArticles", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllArticlesRespons" +
        "e")]
    www.borger.dk._2009.WSArticleExport.v1.types.ArticleDescription[] GetAllArticles();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByID", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByIDRespons" +
        "e")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByIDArticle" +
        "ExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.Article GetArticleByID(int articleID, System.Nullable<int> municipalityCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrl", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrlResp" +
        "onse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrlArti" +
        "cleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription GetArticleIDByUrl(string url);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
        "rviceArea", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
        "rviceAreaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
        "rviceAreaArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsByFormServiceArea(string formServiceAreaNumber, System.Nullable<System.DateTime> updatedAfter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
        "skArea", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
        "skAreaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
        "skAreaArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsByFormTaskArea(string formTaskAreaNumber, System.Nullable<System.DateTime> updatedAfter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
        "s", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
        "sResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
        "sArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.Article[] GetArticlesByFormTasks(string[] formTaskNumbers, System.Nullable<bool> useLogicalAnd, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDs", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDsRespo" +
        "nse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ITST.Borgerdk.Export.Common.WcfContracts.ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDsArtic" +
        "leExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
    www.borger.dk._2009.WSArticleExport.v1.types.Article[] GetArticlesByIDs(int[] articleIDs, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormServiceAreaLis" +
        "t", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormServiceAreaLis" +
        "tResponse")]
    www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] GetFormServiceAreaList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskAreaList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskAreaListRe" +
        "sponse")]
    www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] GetFormTaskAreaList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskListRespon" +
        "se")]
    www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] GetFormTaskList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetMunicipalityList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetMunicipalityListRe" +
        "sponse")]
    www.borger.dk._2009.WSArticleExport.v1.types.Municipality[] GetMunicipalityList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllSites", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllSitesResponse")]
    www.borger.dk._2009.WSArticleExport.v2.types.Site[] GetAllSites();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsBySiteID" +
        "", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsBySiteID" +
        "Response")]
    www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsBySiteID(int siteID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IArticleExportChannel : IArticleExport, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ArticleExportClient : System.ServiceModel.ClientBase<IArticleExport>, IArticleExport
{
    
    public ArticleExportClient()
    {
    }
    
    public ArticleExportClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ArticleExportClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ArticleExportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ArticleExportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.ArticleDescription[] GetAllArticles()
    {
        return base.Channel.GetAllArticles();
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.Article GetArticleByID(int articleID, System.Nullable<int> municipalityCode)
    {
        return base.Channel.GetArticleByID(articleID, municipalityCode);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription GetArticleIDByUrl(string url)
    {
        return base.Channel.GetArticleIDByUrl(url);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsByFormServiceArea(string formServiceAreaNumber, System.Nullable<System.DateTime> updatedAfter)
    {
        return base.Channel.GetArticleIDsByFormServiceArea(formServiceAreaNumber, updatedAfter);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsByFormTaskArea(string formTaskAreaNumber, System.Nullable<System.DateTime> updatedAfter)
    {
        return base.Channel.GetArticleIDsByFormTaskArea(formTaskAreaNumber, updatedAfter);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.Article[] GetArticlesByFormTasks(string[] formTaskNumbers, System.Nullable<bool> useLogicalAnd, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter)
    {
        return base.Channel.GetArticlesByFormTasks(formTaskNumbers, useLogicalAnd, municipalityCode, updatedAfter);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.Article[] GetArticlesByIDs(int[] articleIDs, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter)
    {
        return base.Channel.GetArticlesByIDs(articleIDs, municipalityCode, updatedAfter);
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.FormServiceArea[] GetFormServiceAreaList()
    {
        return base.Channel.GetFormServiceAreaList();
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.FormTaskArea[] GetFormTaskAreaList()
    {
        return base.Channel.GetFormTaskAreaList();
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.FormTask[] GetFormTaskList()
    {
        return base.Channel.GetFormTaskList();
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.Municipality[] GetMunicipalityList()
    {
        return base.Channel.GetMunicipalityList();
    }
    
    public www.borger.dk._2009.WSArticleExport.v2.types.Site[] GetAllSites()
    {
        return base.Channel.GetAllSites();
    }
    
    public www.borger.dk._2009.WSArticleExport.v1.types.ArticleShortDescription[] GetArticleIDsBySiteID(int siteID)
    {
        return base.Channel.GetArticleIDsBySiteID(siteID);
    }
}
