//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:2.0.50727.5466
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

[assembly: ContractNamespace("http://www.borger.dk/2009/WSArticleExport/v1/types", ClrNamespace="www.borger.dk._2009.WSArticleExport.v1.types")]
[assembly: ContractNamespace("http://www.borger.dk/2009/WSArticleExport/v2/types", ClrNamespace="www.borger.dk._2009.WSArticleExport.v2.types")]

namespace Skybrud.Integrations.BorgerDk.WebService
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="ArticleDescription", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class ArticleDescription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        private string ArticleUrlField;
        
        private FormServiceArea[] FormServiceAreasField;
        
        private FormTaskArea[] FormTaskAreasField;
        
        private FormTask[] FormTasksField;
        
        private System.DateTime LastUpdatedField;
        
        private System.DateTime PublishingDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [DataMember()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
        
        [DataMember()]
        public string ArticleUrl
        {
            get
            {
                return this.ArticleUrlField;
            }
            set
            {
                this.ArticleUrlField = value;
            }
        }
        
        [DataMember()]
        public FormServiceArea[] FormServiceAreas
        {
            get
            {
                return this.FormServiceAreasField;
            }
            set
            {
                this.FormServiceAreasField = value;
            }
        }
        
        [DataMember()]
        public FormTaskArea[] FormTaskAreas
        {
            get
            {
                return this.FormTaskAreasField;
            }
            set
            {
                this.FormTaskAreasField = value;
            }
        }
        
        [DataMember()]
        public FormTask[] FormTasks
        {
            get
            {
                return this.FormTasksField;
            }
            set
            {
                this.FormTasksField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime PublishingDate
        {
            get
            {
                return this.PublishingDateField;
            }
            set
            {
                this.PublishingDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="FormServiceArea", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormServiceArea : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormServiceAreaNameField;
        
        private string FormServiceAreaNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string FormServiceAreaName
        {
            get
            {
                return this.FormServiceAreaNameField;
            }
            set
            {
                this.FormServiceAreaNameField = value;
            }
        }
        
        [DataMember()]
        public string FormServiceAreaNumber
        {
            get
            {
                return this.FormServiceAreaNumberField;
            }
            set
            {
                this.FormServiceAreaNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="FormTaskArea", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormTaskArea : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormTaskAreaNameField;
        
        private string FormTaskAreaNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string FormTaskAreaName
        {
            get
            {
                return this.FormTaskAreaNameField;
            }
            set
            {
                this.FormTaskAreaNameField = value;
            }
        }
        
        [DataMember()]
        public string FormTaskAreaNumber
        {
            get
            {
                return this.FormTaskAreaNumberField;
            }
            set
            {
                this.FormTaskAreaNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="FormTask", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class FormTask : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FormTaskNameField;
        
        private string FormTaskNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string FormTaskName
        {
            get
            {
                return this.FormTaskNameField;
            }
            set
            {
                this.FormTaskNameField = value;
            }
        }
        
        [DataMember()]
        public string FormTaskNumber
        {
            get
            {
                return this.FormTaskNumberField;
            }
            set
            {
                this.FormTaskNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="Article", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArticleHeaderField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        private string ArticleUrlField;
        
        private string ContentField;
        
        private FormServiceArea[] FormServiceAreasField;
        
        private FormTaskArea[] FormTaskAreasField;
        
        private FormTask[] FormTasksField;
        
        private System.DateTime LastUpdatedField;
        
        private System.DateTime PublishingDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string ArticleHeader
        {
            get
            {
                return this.ArticleHeaderField;
            }
            set
            {
                this.ArticleHeaderField = value;
            }
        }
        
        [DataMember()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [DataMember()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
        
        [DataMember()]
        public string ArticleUrl
        {
            get
            {
                return this.ArticleUrlField;
            }
            set
            {
                this.ArticleUrlField = value;
            }
        }
        
        [DataMember()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [DataMember()]
        public FormServiceArea[] FormServiceAreas
        {
            get
            {
                return this.FormServiceAreasField;
            }
            set
            {
                this.FormServiceAreasField = value;
            }
        }
        
        [DataMember()]
        public FormTaskArea[] FormTaskAreas
        {
            get
            {
                return this.FormTaskAreasField;
            }
            set
            {
                this.FormTaskAreasField = value;
            }
        }
        
        [DataMember()]
        public FormTask[] FormTasks
        {
            get
            {
                return this.FormTasksField;
            }
            set
            {
                this.FormTasksField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime PublishingDate
        {
            get
            {
                return this.PublishingDateField;
            }
            set
            {
                this.PublishingDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="ArticleShortDescription", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class ArticleShortDescription : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArticleIDField;
        
        private string ArticleTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int ArticleID
        {
            get
            {
                return this.ArticleIDField;
            }
            set
            {
                this.ArticleIDField = value;
            }
        }
        
        [DataMember()]
        public string ArticleTitle
        {
            get
            {
                return this.ArticleTitleField;
            }
            set
            {
                this.ArticleTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="Municipality", Namespace="http://www.borger.dk/2009/WSArticleExport/v1/types")]
    public partial class Municipality : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MunicipalityCodeField;
        
        private string MunicipalityNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int MunicipalityCode
        {
            get
            {
                return this.MunicipalityCodeField;
            }
            set
            {
                this.MunicipalityCodeField = value;
            }
        }
        
        [DataMember()]
        public string MunicipalityName
        {
            get
            {
                return this.MunicipalityNameField;
            }
            set
            {
                this.MunicipalityNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [DataContract(Name="Site", Namespace="http://www.borger.dk/2009/WSArticleExport/v2/types")]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ParentIDField;
        
        private int SiteIDField;
        
        private string SiteNameField;
        
        private string SiteTitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.Nullable<int> ParentID
        {
            get
            {
                return this.ParentIDField;
            }
            set
            {
                this.ParentIDField = value;
            }
        }
        
        [DataMember()]
        public int SiteID
        {
            get
            {
                return this.SiteIDField;
            }
            set
            {
                this.SiteIDField = value;
            }
        }
        
        [DataMember()]
        public string SiteName
        {
            get
            {
                return this.SiteNameField;
            }
            set
            {
                this.SiteNameField = value;
            }
        }
        
        [DataMember()]
        public string SiteTitle
        {
            get
            {
                return this.SiteTitleField;
            }
            set
            {
                this.SiteTitleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [Serializable()]
    public partial class ArticleExportException : FaultExceptionOfArticleFaulttsA8QZpB
    {
        
        public ArticleExportException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [Serializable()]
    [KnownType(typeof(ArticleExportException))]
    public partial class FaultExceptionOfArticleFaulttsA8QZpB : System.ServiceModel.FaultException
    {
        
        public FaultExceptionOfArticleFaulttsA8QZpB(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
            base(info, context)
        {
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.borger.dk/2009/WSArticleExport/v1", ConfigurationName="IArticleExport")]
    public interface IArticleExport
    {
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllArticles", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllArticlesRespons" +
                                                                                                                                                         "e")]
        ArticleDescription[] GetAllArticles();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByID", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByIDRespons" +
                                                                                                                                                         "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleByIDArticle" +
                                                                                                                                    "ExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        Article GetArticleByID(int articleID, System.Nullable<int> municipalityCode);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrl", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrlResp" +
                                                                                                                                                            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDByUrlArti" +
                                                                                                                                    "cleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        ArticleShortDescription GetArticleIDByUrl(string url);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
                                                               "rviceArea", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
                                                                                        "rviceAreaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormSe" +
                                                                                                                                    "rviceAreaArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        ArticleShortDescription[] GetArticleIDsByFormServiceArea(string formServiceAreaNumber, System.Nullable<System.DateTime> updatedAfter);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
                                                               "skArea", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
                                                                                     "skAreaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsByFormTa" +
                                                                                                                                    "skAreaArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        ArticleShortDescription[] GetArticleIDsByFormTaskArea(string formTaskAreaNumber, System.Nullable<System.DateTime> updatedAfter);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
                                                               "s", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
                                                                                "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByFormTask" +
                                                                                                                                    "sArticleExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        Article[] GetArticlesByFormTasks(string[] formTaskNumbers, System.Nullable<bool> useLogicalAnd, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDs", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDsRespo" +
                                                                                                                                                           "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArticleExportException), Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticlesByIDsArtic" +
                                                                                                                                    "leExportExceptionFault", Name="ArticleExportException", Namespace="http://schemas.datacontract.org/2004/07/ITST.Borgerdk.Export.Common.WcfContracts")]
        Article[] GetArticlesByIDs(int[] articleIDs, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormServiceAreaLis" +
                                                               "t", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormServiceAreaLis" +
                                                                                "tResponse")]
        FormServiceArea[] GetFormServiceAreaList();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskAreaList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskAreaListRe" +
                                                                                                                                                              "sponse")]
        FormTaskArea[] GetFormTaskAreaList();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetFormTaskListRespon" +
                                                                                                                                                          "se")]
        FormTask[] GetFormTaskList();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetMunicipalityList", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetMunicipalityListRe" +
                                                                                                                                                              "sponse")]
        Municipality[] GetMunicipalityList();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllSites", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetAllSitesResponse")]
        Site[] GetAllSites();
    
        [System.ServiceModel.OperationContractAttribute(Action="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsBySiteID" +
                                                               "", ReplyAction="http://www.borger.dk/2009/WSArticleExport/v1/IArticleExport/GetArticleIDsBySiteID" +
                                                                               "Response")]
        ArticleShortDescription[] GetArticleIDsBySiteID(int siteID);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IArticleExportChannel : IArticleExport, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ArticleExportClient : System.ServiceModel.ClientBase<IArticleExport>, IArticleExport
    {
    
        public ArticleExportClient()
        {
        }
    
        public ArticleExportClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
        {
        }
    
        public ArticleExportClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public ArticleExportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public ArticleExportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
        {
        }
    
        public ArticleDescription[] GetAllArticles()
        {
            return base.Channel.GetAllArticles();
        }
    
        public Article GetArticleByID(int articleID, System.Nullable<int> municipalityCode)
        {
            return base.Channel.GetArticleByID(articleID, municipalityCode);
        }
    
        public ArticleShortDescription GetArticleIDByUrl(string url)
        {
            return base.Channel.GetArticleIDByUrl(url);
        }
    
        public ArticleShortDescription[] GetArticleIDsByFormServiceArea(string formServiceAreaNumber, System.Nullable<System.DateTime> updatedAfter)
        {
            return base.Channel.GetArticleIDsByFormServiceArea(formServiceAreaNumber, updatedAfter);
        }
    
        public ArticleShortDescription[] GetArticleIDsByFormTaskArea(string formTaskAreaNumber, System.Nullable<System.DateTime> updatedAfter)
        {
            return base.Channel.GetArticleIDsByFormTaskArea(formTaskAreaNumber, updatedAfter);
        }
    
        public Article[] GetArticlesByFormTasks(string[] formTaskNumbers, System.Nullable<bool> useLogicalAnd, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter)
        {
            return base.Channel.GetArticlesByFormTasks(formTaskNumbers, useLogicalAnd, municipalityCode, updatedAfter);
        }
    
        public Article[] GetArticlesByIDs(int[] articleIDs, System.Nullable<int> municipalityCode, System.Nullable<System.DateTime> updatedAfter)
        {
            return base.Channel.GetArticlesByIDs(articleIDs, municipalityCode, updatedAfter);
        }
    
        public FormServiceArea[] GetFormServiceAreaList()
        {
            return base.Channel.GetFormServiceAreaList();
        }
    
        public FormTaskArea[] GetFormTaskAreaList()
        {
            return base.Channel.GetFormTaskAreaList();
        }
    
        public FormTask[] GetFormTaskList()
        {
            return base.Channel.GetFormTaskList();
        }
    
        public Municipality[] GetMunicipalityList()
        {
            return base.Channel.GetMunicipalityList();
        }
    
        public Site[] GetAllSites()
        {
            return base.Channel.GetAllSites();
        }
    
        public ArticleShortDescription[] GetArticleIDsBySiteID(int siteID)
        {
            return base.Channel.GetArticleIDsBySiteID(siteID);
        }
    }
}